# Generated by Django 5.2 on 2026-03-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_placephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='place',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
