# Generated by Django 5.2 on 2026-04-02 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_place_email_place_operating_hours_place_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placephoto',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='category',
            field=models.CharField(choices=[('gallery', 'Art Gallery'), ('museum', 'Museum'), ('thangka', 'Thangka Painting'), ('pottery', 'Pottery & Ceramics'), ('cafe', 'Art Café & Library'), ('workshop', 'Workshop'), ('studio', 'Artist Studio'), ('weaving', 'Weaving & Textile'), ('sculpture', 'Sculpture'), ('photography', 'Photography')], max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('gallery', 'Art Gallery'), ('museum', 'Museum'), ('thangka', 'Thangka Painting'), ('pottery', 'Pottery & Ceramics'), ('cafe', 'Art Café & Library'), ('workshop', 'Workshop'), ('studio', 'Artist Studio'), ('weaving', 'Weaving & Textile'), ('sculpture', 'Sculpture'), ('photography', 'Photography')], max_length=100),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('workshop', 'Workshop'), ('class', 'Class'), ('tour', 'Guided Tour'), ('exhibition', 'Exhibition'), ('performance', 'Performance'), ('talk', 'Artist Talk'), ('retreat', 'Art Retreat')], default='workshop', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_free', models.BooleanField(default=False)),
                ('total_spots', models.IntegerField(default=10)),
                ('spots_taken', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='apps.creatorprofile')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='apps.place')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
