# Generated by Django 5.2 on 2026-04-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
